server:
    port: 8778

debug: true

spring:
    cloud:
        zookeeper:
            connectString: 127.0.0.1:2181
            enabled: false
    sleuth:
        enabled: false

swagger:
    basePackage: com.ctgpaasstringjirttest.controller
    title: ctgpaas-string-jirttest RESTful APIs
    description: ctgpaas-string-jirttest RESTful API
    version: 1.0.0-SNAPSHOT
    openApi:
        group: OpenApi
        basePackage: com.ctgpaasstringjirttest.controller
        title: actgpaas-string-jirttest Open APIs
        description: ctgpaas-string-jirttest Open API
        version: 1.0.0-SNAPSHOT
